#!/bin/bash 

echo "Turning the raspberry pi into AP..."
raspivid -o - -t 0 -hf -w 1024 -h 720 -fps 40 |cvlc -vvv stream:///dev/stdin --sout '#standard{access=http,mux=ts,dst=:8160}' :demux=h264 &  2> /dev/null
sudo hostapd /etc/hostapd/hostapd.conf > ap_log.txt -t &
python3.5 app.py &
